# Generated by Django 5.2.12 on 2026-03-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images',
                                    verbose_name='Фото'),
        ),
    ]
