# Generated by Django 5.2.12 on 2026-03-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_com_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_count',
            field=models.IntegerField(default=0,
                                      verbose_name='Количество комментариев'),
        ),
    ]
